###
GET http://localhost:4000/api/blogs/

###
POST http://localhost:4000/api/blogs
Content-Type: application/json

{
    "title": "Castillo Peach", 
    "description": "Reino Champiñón",
    "category": "Juegos",
    "image": "url-image"
}

###
GET http://localhost:4000/api/blogs/60a46dca883c0c3d08c948de

###
DELETE http://localhost:4000/api/blogs/60a46dca883c0c3d08c948de

###
PUT http://localhost:4000/api/blogs/60a46dca883c0c3d08c948de
Content-Type: application/json

{
    "title": "Castillo Mario"
}


###
POST http://localhost:4000/api/comments/60a517fb78f2f40ac49a7a67
Content-Type: application/json

{
    "idBlog": "60a517fb78f2f40ac49a7a67", 
    "idUser": "Poke 17",
    "comment": "Muy bonito lugar"
}

###
GET http://localhost:4000/api/comments/60a517fb78f2f40ac49a7a67